version: "3.8"

services:
  # webapi:
  #   build:
  #     context: .
  #     dockerfile: src/webapi/Dockerfile
  #   depends_on:
  #     - elasticsearch
  #     - kibana
  #   #   #   - filebeat
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
  #     - DOTNET_RUNNING_IN_COMPOSE=${DOTNET_RUNNING_IN_COMPOSE}
  # #   networks:
  # #     - serilog
  # #   #logging:
  # #   #  driver: none #suppress all logging

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./.docker-compose/elasticsearch/data:/usr/share/elasticsearch/data #Note: if startup fails create these local folders by hand!
      - ./.docker-compose/elasticsearch/logs:/usr/share/elasticsearch/logs #Note: if startup fails create these local folders by hand!
    environment:
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    # networks:
    #   - serilog

  # logstash-src:
  #   image: docker.elastic.co/logstash/logstash:7.11.1
  #   ports:
  #     - 8080:8080
  #   # volumes:
  #   #   - ./.docker-compose/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
  #   #   - ./.docker-compose/logstash/pipeline:/usr/share/logstash/pipeline:ro
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   depends_on:
  #     - elasticsearch
  #   # networks:
  #   #   - serilog

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      #- elasticsearch_URL=http://localhost:9200
      - SERVER_NAME=http://localhost:5601
      - elasticsearch_HOSTS=http://localhost:9200
    # networks:
    #   - serilog

  # #https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html
  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:7.9.3
  #   depends_on:
  #     - elasticsearch
  #   user: root
  #   volumes:
  #     - ./.docker-compose/filebeat/data:/usr/share/filebeat/data:rw
  #     #- ./.docker-compose/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  #     - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /var/lib/docker:/var/lib/docker:ro
  #   networks:
  #     - serilog
  #https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&preserve-view=true&pivots=cs1-powershell
  #https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-deployment
  #docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Pas.sword@12345" -p 1433:1433 --name mssql -h mssql --rm -it mcr.microsoft.com/mssql/server:2019-latest
  mssql:
    #image: mcr.microsoft.com/mssql/server:2019-latest
    build:
      context: .
      dockerfile: src/mssql/Dockerfile
    restart: always
    ports:
      - 1433:1433
    volumes:
      - ./.docker-compose/mssql/data:/var/opt/mssql/data
      - ./.docker-compose/mssql/log:/var/opt/mssql/log
      - ./.docker-compose/mssql/secrets:/var/opt/mssql/secrets
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pas.sword@12345
    # networks:
    #   - serilog

  seq:
    image: datalust/seq
    restart: always
    ports:
      - 5342:80 #web ui
      - 5341:5341 #ingestion
    volumes:
      - ./.docker-compose/seq/data:/data/
    environment:
      - ACCEPT_EULA=Y
      - BASE_URI=http://localhost:5342

  loki:
    image: grafana/loki
    restart: always
    ports:
      - 3100:3100

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - /.docker-compose/redis:/data
    entrypoint: redis-server --appendonly yes

  p3x:
    image: patrikx3/p3x-redis-ui
    ports:
      - 7843:7843
    volumes:
      - /.docker-compose/p3x-redis-ui-settings:/settings
    depends_on:
      - redis

networks:
  serilog:
    driver: bridge
    #external: true
