version: '3.8'  

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    ports:
    - 9200:9200
    volumes:
    - /c/temp/_DockerCompose/elasticsearch-data:/usr/share/elasticsearch/data
    environment:  
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
    networks:
    - elastic
  
  kibana:  
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch
    environment:
    - ELASTICSEARCH_URL=http://localhost:9200
    networks:
    - elastic

  workerservice:
    container_name: workerservice
    build:
       context: .
       dockerfile: src/WorkerService/Dockerfile
    depends_on:
    - elasticsearch
    - kibana

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.0
    container_name: filebeat
    depends_on:
    - elasticsearch
    #user: root
    volumes:
    - /c/temp/_DockerCompose/filebeat/data:/usr/share/filebeat/data:rw
    - /c/temp/_DockerCompose/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker:/var/lib/docker:ro
    #networks:
    #- elastic


networks:
  elastic:
    driver: bridge
  
volumes:
  elasticsearch-data: