filebeat.inputs:
#https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-container.html
- type: container
  #stream: all #Reads from the specified streams only: all, stdout or stderr. The default is all
  paths: 
  - '/var/lib/docker/containers/*/*.log'
  #exclude_lines: ['^DBG']
  #include_lines: ['^ERR', '^WARN']
# - type: log
#   paths:
#   - '/var/lib/docker/containers/*/*.log'
#   json.message_key: log
#   json.keys_under_root: true
#   processors:
#   - add_docker_metadata: ~

processors:
#https://www.elastic.co/guide/en/beats/filebeat/master/add-docker-metadata.html
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"
#https://www.elastic.co/guide/en/beats/filebeat/master/add-kubernetes-metadata.html
# - add_kubernetes_metadata:
#     default_indexers.enabled: false
#     default_matchers.enabled: false

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
  - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

#logging.level: debug
logging.to_files: true
logging.to_syslog: false
logging.to_stderr: true
logging.json: true
logging.metrics.enabled: false


setup.kibana:
  host: "kibana:5601" 
  #username: "my_kibana_user"  
  #password: "{pwd}"